name: ReunionPal
version: 1.0Alpha
main: mc.reunion.ReunionPal.PluginLoader
authors: [Mrwener]
description: 'Developed with love for reunion.eu by MrWener ^^.'
commands:
 pal:
  usage: </command>
  aliases: [mcreunion, mcr, reunion]